### ISSUE TITLE
Question about implementation of admix

### ISSUE THREAD

**Issue by chawins** [ZhengyuZhao/TransferAttackEval#1]
I noticed a potential difference between the Admix paper and the re-implementation here. The code [here](https://github.com/ZhengyuZhao/TransferAttackEval/blob/main/attacks/input_augmentation_attacks.py#L317) uses `img_x + 0.2 * img_other` as inputs to the model (see code below) which may be missing the $\gamma_i = 1/2^i$ factor from Eq. 3 in [the paper](https://arxiv.org/pdf/2102.00436.pdf).

```python
...
for c in range(multi_copies):
    img_other = img[torch.randperm(img.shape[0])].view(img.size())
    logits = model(img_x + 0.2 * img_other)
    loss = nn.CrossEntropyLoss(reduction='sum')(logits,labels)
    loss.backward()
    input_grad = input_grad + img_x.grad.clone()
...
```

I could be totally missing something here too so please correct me if I'm wrong. Thanks!

**Comment by ZhengyuZhao** [comment]
> I noticed a potential difference between the Admix paper and the re-implementation here. The code [here](https://github.com/ZhengyuZhao/TransferAttackEval/blob/main/attacks/input_augmentation_attacks.py#L317) uses `img_x + 0.2 * img_other` as inputs to the model (see code below) which may be missing the γi=1/2i factor from Eq. 3 in [the paper](https://arxiv.org/pdf/2102.00436.pdf).
> 
> ```python
> ...
> for c in range(multi_copies):
>     img_other = img[torch.randperm(img.shape[0])].view(img.size())
>     logits = model(img_x + 0.2 * img_other)
>     loss = nn.CrossEntropyLoss(reduction='sum')(logits,labels)
>     loss.backward()
>     input_grad = input_grad + img_x.grad.clone()
> ...
> ```
> 
> I could be totally missing something here too so please correct me if I'm wrong. Thanks!

Hi Chawins,

Thanks for your interest in our work. Yes, there is indeed a difference and we did it on purpose. As stated in our paper, one of our main contributions is to conduct a fair comparison by isolating the contribution of the core algorithm of each attack method. Accordingly, for the five input transformation attacks, we focus on the algorithm of input transformations and evaluate how different transformations compare with each other.

Specifically, for Admix, the core algorithm is the mixup transformation. As described in the original Admix work, the $\gamma_i = 1/2^i$ is used to implement another (transformation-based) algorithm, SIM. So we omit it by setting $i=0$.

If you have any other questions, feel free to ask.

**Comment by chawins** [comment]
Thank you! Maybe one more question is choosing the other image ($x'$) with `img_other = img[torch.randperm(img.shape[0])].view(img.size())` does not necessarily guarantee that the other image will come from a different class from `img` right? But the original paper says that $x'$ comes from another category. Is this part also intentional?

**Comment by ZhengyuZhao** [comment]
> Thank you! Maybe one more question is choosing the other image ($x'$) with `img_other = img[torch.randperm(img.shape[0])].view(img.size())` does not necessarily guarantee that the other image will come from a different class from `img` right? But the original paper says that x′ comes from another category. Is this part also intentional?

This part is not intentional but is just used to make the implementation of data loading simpler. Since we have a large dataset of 5000 images with 5 images per ImageNet class, this random selection from the whole dataset will very likely (4995/5000=99.9%) choose an image from a different class. So the difference in the final results is negligible. Thanks for pointing out this detail, and I will add a comment for that line of code to make it clear.

**Comment by chawins** [comment]
I see. That makes sense for ImageNet. Thank you for all the clarifications!
