### ISSUE TITLE
A question about AAI re-implementation

### ISSUE THREAD

**Issue by GewelsJI** [ZhengyuZhao/TransferAttackEval#2]
Hi, @ZhengyuZhao 

Thank you for your nice work. I have a question for this [line](https://github.com/ZhengyuZhao/TransferAttackEval/blob/00ce4d8d9e5da6830b7240137c1ef89068d614e9/attacks/utils_iaa.py#L255) of AAI model. Could you explain the reason of adding `nn.LeakyReLU` here?

Hope you are doing well.

Best,
Gepeng.

**Comment by ZhengyuZhao** [comment]
> 

Hi Gepeng,

Thank you for your interest in our work. We got the source code from the authors of IAA without further cleaning. As can be seen from line 63, the negative_slope is set as 1, which means that LeakyReLU was actually not functioning (e.g., in lines 104 and 169) but just acting as an identity mapping function. We suppose the original authors might explore other values for negative_slope but did not discuss it in their paper.

Best,
Zhengyu

**Comment by ZhengyuZhao** [comment]
> Hi, @ZhengyuZhao
> 
> Thank you for your nice work. I have a question for this [line](https://github.com/ZhengyuZhao/TransferAttackEval/blob/00ce4d8d9e5da6830b7240137c1ef89068d614e9/attacks/utils_iaa.py#L255) of AAI model. Could you explain the reason of adding `nn.LeakyReLU` here?
> 
> Hope you are doing well.
> 
> Best, Gepeng.

Hi Gepeng,

Thank you for your interest in our work. We got the source code from the authors of IAA without further cleaning. As can be seen from line 63, the negative_slope is set as 1, which means that LeakyReLU was actually not functioning (e.g., in lines 104 and 169) but just acting as an identity mapping function. We suppose the original authors might explore other values for negative_slope but did not discuss it in their paper.

Best,
Zhengyu

**Comment by GewelsJI** [comment]
Cool. I get your idea. 

Thanks.
