### ISSUE TITLE
Loaded Checkpoint of RFA

### ISSUE THREAD

**Issue by zhengmeixi** [ZhengyuZhao/TransferAttackEval#4]
Hi,
Thanks for your excellent work! 
I'd like to reproduce RFA. I noticed that you load a checkpoint model for implementation of this method. Can you kindly share this checkpoint?

**Comment by ZhengyuZhao** [comment]
> Hi, Thanks for your excellent work! I'd like to reproduce RFA. I noticed that you load a checkpoint model for implementation of this method. Can you kindly share this checkpoint?

Hi, thanks for your interest! We follow the original work of RFA to use the pre-trained models provided in this link: https://github.com/microsoft/robust-models-transfer. Specifically, in an updated version of our paper (which will appear tomorrow on arXiv), we report results for both L2-Robust ImageNet with ResNet50 ε=0.1 and inf-Robust ImageNet with ResNet50 ε=8.
