### ISSUE TITLE
特征攻击中间层怎么选择呢，只给了resnet50的中间层，其他几个模型运行的时候怎么设置参数呢？

### ISSUE THREAD

**Issue by tfdee123** [ZhengyuZhao/TransferAttackEval#6]

**Comment by ZhengyuZhao** [comment]
> _No description provided._

在文章中我们只选取了ResNet作为surrogate model，所以不涉及其他模型中间层的选取。或许你可以从特征攻击那几篇文章中找到相关的讨论。
