### ISSUE TITLE
Will the code of defense be released in the future?

### ISSUE THREAD

**Issue by mo666666** [ZhengyuZhao/TransferAttackEval#9]
Hello, zhengyu! Thank you for your excellent work. I wonder whether the code of defense will be released in the future. 

Sincerely, look forward to your reply.

**Comment by ZhengyuZhao** [comment]
> Hello, zhengyu! Thank you for your excellent work. I wonder whether the code of defense will be released in the future.
> 
> Sincerely, look forward to your reply.

Hi Yichuan,

Thanks for your interest in our work! For those defenses, we directly use their open-source codes.

**Comment by mo666666** [comment]
Thank you for your kind response. Would you mind providing the Github link of the related codes for me? It is of vital importance to my current research.

**Comment by ZhengyuZhao** [comment]
I have not gathered the links to their code...but you can refer to Appendix A.2 in our paper to find the code in their original paper. If it is difficult to find any code, feel free to contact me.

**Comment by ZhengyuZhao** [comment]
> Thank you for your kind response. Would you mind providing the Github link of the related codes for me? It is of vital importance to my current research.


I have not gathered the links to their code...but you can refer to Appendix A.2 in our paper to find the code in their original paper. If it is difficult to find any code, feel free to contact me.

**Comment by mo666666** [comment]
Ok, I will refer to the Appendix to access the relevant code.
Thank you again for your assistance.
Wish you have a nice day!

**Comment by ZhengyuZhao** [comment]
> Ok, I will refer to the Appendix to access the relevant code. Thank you again for your assistance. Wish you have a nice day!

Have a nice day and good luck!
